apiVersion: apps/v1
kind: Deployment
metadata:
  name: voyage-analytics-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: voyage-analytics
  template:
    metadata:
      labels:
        app: voyage-analytics
    spec:
      containers:
      - name: voyage-analytics-container
        image: senaniket/voyage-analytics:latest
        ports:
        - containerPort: 8000
        env:
        - name: MLFLOW_TRACKING_URI
          value: "https://unbalanced-phantasmagorianly-merrie.ngrok-free.dev"
        - name: MLFLOW_HTTP_REQUEST_HEADERS
          value: '{"ngrok-skip-browser-warning": "true"}'